disabled_rules:
  - line_length
  - type_name
  - todo
  - valid_docs
  - function_parameter_count
  - cyclomatic_complexity
  - function_body_length
  - conditional_binding_cascade

opt_in_rules:
  - empty_count
  - force_unwrapping

excluded:
  - Pods
  - iOSInjectionProject
  - PaketeTests

force_cast: warning
file_length:
  warning: 400
  error: 600

variable_name:
  max_length: 100
  excluded:
  - a
  - b
